### ISSUE TITLE
Socketlib v1.0.11 won't install on Foundry VTT v10

### ISSUE THREAD

**Issue by sparkyeenh** [manuelVo/foundryvtt-socketlib#11]
Foundry VTT console below:

setup.js:292 Error: Unable to load valid module manifest data from "https://raw.githubusercontent.com/manuelVo/foundryvtt-socketlib/v1.0.11/module.json"
The requested manifest at "https://raw.githubusercontent.com/manuelVo/foundryvtt-socketlib/v1.0.11/module.json" did not provide module manifest data.
    at Module.installPackage (file:///F:/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1620)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SetupView.handlePost (file:///F:/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:1980)

**Comment by EndlessFractal** [comment]
> https://github.com/manuelVo/foundryvtt-socketlib/archive/v1.0.11.zip 

Does not exist. 404 error. Probably have to wait for it to be uploaded.

**Comment by Gawdl3y** [comment]
Looks like they updated the manifest with the download URL for the new version, but did not actually tag the release and publish it.

**Comment by Keifeto** [comment]
just wanted to note that it is still not working after 3 hours since the last comment

**Comment by manuelVo** [comment]
Should be fixed now.
